### ISSUE TITLE
Implement language toggle besides search box

### ISSUE THREAD

**Issue by Maddoxx88** [Maddoxx88/microregex#22]
#### TODO

- [ ] Add javascript and python in the dropdown selector
- [ ] Dropdown should have icon with text

**Comment by manav-06** [comment]
@Maddoxx88 Can you assign this to me?

**Comment by Maddoxx88** [comment]
> @Maddoxx88 Can you assign this to me?

No, we have registered this project as an idea [here](https://hustles.reactplay.io/hackrplay/2022/home). If you want to contribute, I'd recommend submitting a PR in one of [these](https://up-for-grabs.net/#/) projects. Happy coding :)
