### ISSUE TITLE
Cards layout and click to copy

### ISSUE THREAD

**Issue by localhoax** [Maddoxx88/microregex#4]
#### TODO:
- Add cards layout
- Click to copy text

**Comment by imanpalsingh** [comment]
Is this deployed somewhere?

**Comment by Maddoxx88** [comment]
> Is this deployed somewhere?

No, we have registered this project as an idea [here](https://hustles.reactplay.io/hackrplay/2022/home). If you want to contribute, I'd recommend submitting a PR in one of [these](https://up-for-grabs.net/#/) projects. Happy coding :)
